spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5


jenkins:
  build:
    util:
      config:
        username: boyameng
        password: axKHBPeK4XsIW
        test-address:
          weaver-operation-platform-sqlserver: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-oracle: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-oracle: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-PG: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-PG: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-达梦: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-达梦: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-神通: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-神通: http://yourIp:8080/job/weaver-operation-platform
        release-address:
          weaver-customer-service-mysql: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-mysql: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-sqlserver: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-sqlserver: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-oracle: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-oracle: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-PG: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-PG: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-DM: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-DM: http://yourIp:8080/job/weaver-operation-platform
          weaver-customer-service-ST: http://yourIp:8080/job/weaver-customer-service
          weaver-operation-platform-ST: http://yourIp:8080/job/weaver-operation-platform
        tokens:
          http://10.12.101.10:8080: 11ec8c8e3e021ffcfc48f91f758fe6d40d
          http://10.12.101.37:8080: 118894759ed2e2815e795d8cdee2fe09ab
          http://10.12.101.34:8080: 1117b5544962eafd0187a82d6e784d5f26
          http://10.12.101.43:8080: 11351527f2f4bb99109e36971a769b3e21
          http://10.12.101.41:8080: 114c4de9eac19d7c914dcd0763856c3466
          http://10.12.101.40:8080: 1180ad38c514aec9ed945765fa051c1d58
          http://10.12.102.100:8080: 117c50c13d50a9492817eb0009191a5c4f
          http://10.12.106.140:8080: 11e995f294993610f6dc04c02dbc968433
          http://10.12.106.130:8080: 116f1a33cdf6e951127dcebb254db50971
          http://10.12.106.170:8080: 11f691ae7e621024015f69126a5f89ee93